import "./globals.css";
import { Tektur } from 'next/font/google';

const tektur = Tektur({ 
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
});

export const metadata = {
  title: "Room Illustration using ThreeJs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={tektur.className} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}